# Generated by Django 5.2 on 2025-05-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100)),
                ('name_official', models.CharField(max_length=200)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('calling_code', models.CharField(blank=True, max_length=20, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('area', models.FloatField(blank=True, null=True)),
                ('flag_png', models.URLField(blank=True, max_length=300, null=True)),
                ('flag_svg', models.URLField(blank=True, max_length=300, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('un_member', models.BooleanField(default=False)),
                ('independent', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name_common'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='codefusion.country')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='codefusion.country')),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borders', to='codefusion.country')),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighboring_countries', to='codefusion.country')),
            ],
            options={
                'unique_together': {('country', 'neighbor')},
            },
        ),
    ]
